# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- develop
- master

pool:
  name: Default

steps:
- script: |
    echo "Checking Docker setup..."
    docker --version
    docker-compose --version
  displayName: Verify Docker Installation

steps:
  - task: CmdLine@2
    displayName: Build and Deploy
    inputs:
      script: |
          docker-compose -f ./deploy/docker-compose-dev.yml -p "develop" build
          docker-compose -f ./deploy/docker-compose-dev.yml -p "develop" up -d

