# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- develop
- master

pool:
  name: Default

variables:
  system.debug: true

steps:
- script: |
    echo "Checking Docker setup..."
    docker --version
    docker-compose --version
  displayName: Verify Docker Installation

- script: |
    echo "Debugging build context..."
    echo "Current directory: $(pwd)"
    cat ./deploy/docker/docker-compose-dev.yml
    cat ./deploy/docker/dev/Dockerfile
  displayName: Debug Build Context

- script: |
      echo "build docker image"
      echo "Current directory: $(pwd)"
      echo "Directory contents:"
      docker-compose -f ./deploy/docker/docker-compose-dev.yml -p "develop" build
      docker-compose -f ./deploy/docker/docker-compose-dev.yml -p "develop" up -d

      

